services:

  opensearch:
    image: opensearchproject/opensearch:3.8.0
    container_name: opensearch

    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g

    ports:
      - "9200:9200"
      - "9600:9600"

    volumes:
      - opensearch-data:/usr/share/opensearch/data


  backend:
    build: ./
    container_name: copilot-backend

    ports:
      - "8000:8000"

    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

    depends_on:
      - opensearch


volumes:
  opensearch-data: