FROM public.ecr.aws/lambda/python:3.11

COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}/requirements-lambda.txt

RUN pip install \
    --no-cache-dir \
    -r ${LAMBDA_TASK_ROOT}/requirements-lambda.txt

COPY app ${LAMBDA_TASK_ROOT}/app

CMD ["app.backend.main.handler"]